"""Render writing prompts as a beautiful HTML email."""
from datetime import date


_CSS = """
* { margin: 0; padding: 0; box-sizing: border-box; }
body {
  background: #0f0f0f;
  font-family: Georgia, 'Times New Roman', serif;
  color: #e8e8e8;
  padding: 0;
}
.wrapper {
  max-width: 600px;
  margin: 0 auto;
  padding: 32px 24px;
}
.header {
  text-align: center;
  margin-bottom: 36px;
  padding-bottom: 24px;
  border-bottom: 1px solid #2a2a2a;
}
.header h1 {
  font-size: 1.1rem;
  font-weight: 400;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  color: #888;
  margin-bottom: 6px;
}
.header .date {
  font-size: 0.85rem;
  color: #555;
  font-family: system-ui, sans-serif;
}
.card {
  margin-bottom: 24px;
  border-radius: 6px;
  overflow: hidden;
  border: 1px solid #222;
}
.card-header {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 10px 16px;
  font-family: system-ui, sans-serif;
  font-size: 0.75rem;
  font-weight: 700;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: #ccc;
}
.card-body {
  background: #161616;
  padding: 20px 20px 22px;
  font-size: 1.05rem;
  line-height: 1.75;
  color: #ddd;
}
.footer {
  margin-top: 36px;
  padding-top: 20px;
  border-top: 1px solid #1e1e1e;
  font-family: system-ui, sans-serif;
  font-size: 0.72rem;
  color: #444;
  text-align: center;
  line-height: 1.6;
}
"""


def render_email(prompts: dict[str, str], genres: dict) -> str:
    today = date.today().strftime("%A, %B %-d, %Y")

    cards = []
    for key, text in prompts.items():
        g = genres.get(key, {})
        icon = g.get("icon", "✦")
        label = g.get("label", key.title())
        color = g.get("color", "#1a1a1a")
        cards.append(f"""
  <div class="card">
    <div class="card-header" style="background: {color};">
      <span>{icon}</span>
      <span>{label}</span>
    </div>
    <div class="card-body">{text}</div>
  </div>""")

    cards_html = "\n".join(cards)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Daily Writing Spark — {today}</title>
  <style>{_CSS}</style>
</head>
<body>
  <div class="wrapper">
    <div class="header">
      <h1>✦ Daily Writing Spark</h1>
      <div class="date">{today}</div>
    </div>
    {cards_html}
    <div class="footer">
      Generated by creative-tools &middot; GitHub Models &middot; {today}
    </div>
  </div>
</body>
</html>"""
