"""Render writing prompts as a beautiful HTML page."""
from datetime import date


_CSS = """
* { margin: 0; padding: 0; box-sizing: border-box; }
body {
  background: #0f0f0f;
  font-family: Georgia, 'Times New Roman', serif;
  color: #e8e8e8;
  padding: 0;
}
.wrapper {
  max-width: 620px;
  margin: 0 auto;
  padding: 32px 24px;
}
.header {
  text-align: center;
  margin-bottom: 36px;
  padding-bottom: 24px;
  border-bottom: 1px solid #2a2a2a;
}
.header h1 {
  font-size: 1.1rem;
  font-weight: 400;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  color: #888;
  margin-bottom: 6px;
}
.header .date {
  font-size: 0.85rem;
  color: #555;
  font-family: system-ui, sans-serif;
}

/* ── Story starter cards ─────────────────────────────────────────────── */
.card {
  margin-bottom: 32px;
  border-radius: 8px;
  overflow: hidden;
  border: 1px solid #252525;
}
.card-header {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 10px 16px;
  font-family: system-ui, sans-serif;
  font-size: 0.75rem;
  font-weight: 700;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: #ccc;
}
.card-header .voice-badge {
  margin-left: auto;
  font-weight: 400;
  opacity: 0.55;
  text-transform: none;
  letter-spacing: 0;
}
.card-lens {
  background: #111;
  padding: 7px 16px;
  font-family: system-ui, sans-serif;
  font-size: 0.72rem;
  color: #555;
  font-style: italic;
  border-bottom: 1px solid #1e1e1e;
}

/* ── Three-part story body ───────────────────────────────────────────── */
.card-body {
  background: #161616;
}
.story-row {
  display: flex;
  padding: 16px 20px;
  border-bottom: 1px solid #1e1e1e;
  gap: 14px;
}
.story-row:last-child {
  border-bottom: none;
}
.story-label {
  font-family: system-ui, sans-serif;
  font-size: 0.62rem;
  font-weight: 700;
  letter-spacing: 0.14em;
  text-transform: uppercase;
  color: #555;
  min-width: 80px;
  padding-top: 3px;
  flex-shrink: 0;
}
.story-text {
  font-size: 1.0rem;
  line-height: 1.7;
  color: #ddd;
}

/* Conflict gets special weight */
.story-row.conflict {
  background: #121212;
  padding-top: 18px;
  padding-bottom: 20px;
}
.story-row.conflict .story-label {
  color: #664422;
}
.story-row.conflict .story-text {
  color: #e8d8c8;
  font-size: 1.05rem;
}

/* ── Footer ──────────────────────────────────────────────────────────── */
.footer {
  margin-top: 36px;
  padding-top: 20px;
  border-top: 1px solid #1e1e1e;
  font-family: system-ui, sans-serif;
  font-size: 0.72rem;
  color: #444;
  text-align: center;
  line-height: 1.6;
}
"""


def _starter_card(key: str, card: dict, genre: dict, voice: str | None, influence: str | None) -> str:
    icon = genre.get("icon", "✦")
    label = genre.get("label", key.title())
    color = genre.get("color", "#1a1a1a")

    voice_badge = (
        f'<span class="voice-badge">{voice}</span>'
        if voice else ""
    )
    lens_row = (
        f'<div class="card-lens">via {influence}</div>'
        if influence else ""
    )

    protagonist = card.get("protagonist", "")
    antagonist = card.get("antagonist", "")
    setting = card.get("setting", "")
    conflict = card.get("conflict", "")

    return f"""
  <div class="card">
    <div class="card-header" style="background: {color};">
      <span>{icon}</span>
      <span>{label}</span>
      {voice_badge}
    </div>
    {lens_row}
    <div class="card-body">
      <div class="story-row">
        <div class="story-label">Protagonist</div>
        <div class="story-text">{protagonist}</div>
      </div>
      <div class="story-row">
        <div class="story-label">Antagonist</div>
        <div class="story-text">{antagonist}</div>
      </div>
      <div class="story-row">
        <div class="story-label">Setting</div>
        <div class="story-text">{setting}</div>
      </div>
      <div class="story-row conflict">
        <div class="story-label">Conflict</div>
        <div class="story-text">{conflict}</div>
      </div>
    </div>
  </div>"""


def render_email(
    cards: dict[str, dict],
    genres: dict,
    voice_map: dict | None = None,
    influence_map: dict | None = None,
) -> str:
    today = date.today().strftime("%A, %B %-d, %Y")

    cards_html = "\n".join(
        _starter_card(
            key,
            card,
            genres.get(key, {}),
            (voice_map or {}).get(key),
            (influence_map or {}).get(key),
        )
        for key, card in cards.items()
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Daily Writing Spark — {today}</title>
  <style>{_CSS}</style>
</head>
<body>
  <div class="wrapper">
    <div class="header">
      <h1>✦ Daily Writing Spark</h1>
      <div class="date">{today}</div>
    </div>
    {cards_html}
    <div class="footer">
      Generated by creative-tools &middot; GitHub Models &middot; {today}
    </div>
  </div>
</body>
</html>"""
